add_newline = false

command_timeout = 1000

[time]
disabled = false

[battery]
disabled = true

[env_var.AWS_PROFILE]
variable = 'AWS_PROFILE'
default = ''
style = "#e2a478"
format = "[$env_value]($style) "
