## pet
[[snippets]]
description = "open pet snippet file"
command = "nvim ~/.config/pet/my_snippet.toml"
output = ""

[[snippets]]
description = "open pet local snippet file"
command = "nvim ~/.config/pet/local.toml"
output = ""

[[snippets]]
description = "launch deepseek-r1:70b"
command = "ollama run deepseek-r1:70b"
output = ""

[[snippets]]
description = "update codex cli"
command = "npm i -g @openai/codex"
output = ""

[[snippets]]
description = "update cluade code"
command = "cluade update"
output = ""

[[snippets]]
description = "update gemini"
command = "npm i -g @google/gemini-cli"
output = ""

[[snippets]]
description = "update kiro-cli"
command = "curl -fsSL https://cli.kiro.dev/install | bash"
output = ""

[[snippets]]
description = "activate uv venv"
command = "echo 'source .venv/bin/activate' > .envrc && direnv allow"
output = ""

[[snippets]]
description = "codex read only"
command = "codex --sandbox read-only --ask-for-approval on-request"
output = ""

[[snippets]]
description = "codex write"
command = "codex --sandbox workspace-write --ask-for-approval on-request"
output = ""

[[snippets]]
description = "ccusage claude"
command = "npx ccusage@latest"
output = ""

[[snippets]]
description = "codex claude"
command = "npx @ccusage/codex@latest"
output = ""

[[snippets]]
description = "1password op siginin"
command = "eval $(op signin)"
output = ""

[[snippets]]
description = "git yearly commit counts"
command = "git log --date=format:%Y --pretty=format:%ad | sort | uniq -c"
output = ""
