model = "gpt-5.1-codex"
web_search_request = true

[notice]
hide_gpt5_1_migration_prompt = true


[mcp_servers.aws_api_mcp_server]
startup_timeout_sec = 300
command = "uvx"
args = ["awslabs.aws-api-mcp-server@latest"]
env = {"AWS_REGION" = "ap-northeast-1"}

[mcp_servers.terraform_mcp_server]
startup_timeout_sec = 300
command = "docker"
args = ["run", "-i", "--rm", "hashicorp/terraform-mcp-server:latest"]
